# -*- coding: utf-8 -*-
"""
Created on Mon Jun 19 17:07:26 2017

@author: bosesaur
"""

import pyodbc
import pandas as pd
import time
import datetime

start = time.time()
conn = pyodbc.connect(DSN="ProsUAT",uid="fanlinli",pwd="jun2017avis")

sql = "select LOC.COUNTRY, LOC.REGION, LOC.POOL, LOC.MARKET_GROUP,FCS.BRAND, FCS.DFP_SUPER_SEGMENT, \
FCS.FCST_DATE, LOC.NON_REV_INDICATOR,LOC.OPEN_LOCATION_IND, \
SUM(FCS.CURRENT_STRATEGY_DEMAND + FCS.FREESELL_UNINFL + FCS.YIELDABLE_UNINFL) AS CURR_STRAT_FCST,\
SUM(FCS.STRATEGY_7_UNINFL + FCS.FREESELL_UNINFL + FCS.YIELDABLE_UNINFL) AS STRAT_7, \
SUM(FCS.STRATEGY_7_UNINFL + FCS.INC_STRATEGY_6_UNINFL + FCS.INC_STRATEGY_5_UNINFL + \
FCS.INC_STRATEGY_4_UNINFL + FCS.INC_STRATEGY_3_UNINFL + FCS.INC_STRATEGY_2_UNINFL + \
FCS.INC_STRATEGY_1_UNINFL + FCS.FREESELL_UNINFL + FCS.YIELDABLE_UNINFL) AS STRAT_1, \
SUM(TOTAL_DEMAND_TO_COME) AS TOTAL_DTC \
FROM PPSS.PA_FCS_DS_RPT FCS INNER JOIN PPSS.PA_CHECKOUT_LOCATION LOC \
ON FCS.DW_STATION = LOC.DW_STATION WHERE LOC.MARKET_GROUP IN ('JFK_T1','EWR_T1','MCO_T1','PHL_T1',\
'IAH_T1','ORD_T1','MSY_T1','LAX_T1','SFO_T1','DFW_T1', \
'MSP_T1','PDX_T1','PIT_T1','BNA_T1','IND_T1','SEA_T1','ABQ_T1','STL_T1','CVG_T1','CLE_T1') \
AND LOC.NON_REV_INDICATOR = 0 AND LOC.OPEN_LOCATION_IND =1 \
GROUP BY LOC.COUNTRY, LOC.REGION,LOC.POOL, \
LOC.MARKET_GROUP,FCS.BRAND, FCS.DFP_SUPER_SEGMENT, \
FCS.FCST_DATE, LOC.NON_REV_INDICATOR,LOC.OPEN_LOCATION_IND"

d = pd.read_sql_query(sql,conn)


writer = pd.ExcelWriter("pros_forecast_{}.xlsx".format(datetime.datetime.today().strftime('%Y-%m-%d')),engine = "xlsxwriter")
d.to_excel(writer)
writer.save()

conn.close()

print "Took :", time.time()-start, "s" 